
export const ARB_GLOBAL = {};

ARB_GLOBAL.MIN_PROFIT_PER_ARB = 50000;   // WEI
ARB_GLOBAL.MAX_GAS_PER_ARB    = 10;      // GWEI

ARB_GLOBAL.NUM_BASE           = 10;
ARB_GLOBAL.HEX_BASE           = 16;
ARB_GLOBAL.ETHEREUM_UNIT      = 1e18;
ARB_GLOBAL.ETHEREUM_PRECISION = 18;
ARB_GLOBAL.GAS_UNIT           = 1e9;
ARB_GLOBAL.GAS_PRECISION      = 9;
ARB_GLOBAL.GSN_UNIT           = 1e8;
ARB_GLOBAL.GSN_PRECISION      = 8;

ARB_GLOBAL.EXEC_INTERVAL      = 9000;         // Milli-seconds
ARB_GLOBAL.RECEIPT_INTERVAL   = 3000;

ARB_GLOBAL.MAX_GAS_PER_ARB_GWEI = ARB_GLOBAL.MAX_GAS_PER_ARB * ARB_GLOBAL.GAS_UNIT;
